# Generated by Django 2.1.7 on 2019-03-03 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('dataTimeStart', models.DateTimeField()),
                ('dataTimeFinish', models.DateTimeField()),
                ('comp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backHome.Company')),
            ],
        ),
    ]
