# Generated by Django 2.1.7 on 2019-03-03 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backHome', '0003_auto_20190303_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='userName',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='userPass',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='dataTimeFinish',
            field=models.DateTimeField(blank=True, default=datetime.datetime, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='dataTimeStart',
            field=models.DateTimeField(blank=True, default=datetime.datetime, null=True),
        ),
    ]
